# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mike Prosper
tagline:          ''
description:      ''
url:              http://mikeprosper.com

author:
  name:           'Mike Prosper'
  url:            https://twitter.com/mlprosper

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mlprosper
